name: Build Custom-Nameplates

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17, 21]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Add execute permission to gradlew
        run: chmod +x ./gradlew  # 关键步骤：赋予gradlew执行权限
      
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: custom-nameplates-build-${{ matrix.java-version }}
          path: target/*.jar
      
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
